apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ping-deployment
spec:
  selector:
    matchLabels:
      app: goping
  replicas: 1
  template:
    metadata:
      labels:
        app: goping
    spec:
      containers:
      - name: goping
        image: ashutoshsinha/go-ping:1.0
        ports:
        - containerPort: 3000
          protocol: TCP